### PR TITLE
Updated relocation tests with cv32e40pv2 encodings

### PR DESCRIPTION
**Pull request by MaryBennett**
Files Changed:

ld/testsuite/ld-riscv-elf:
 * cv-bi-beqimm.d: Updated encoding of CORE-V instruction.
 * cv-bi-bneimm.d: Likewise.

==Results==
===LD===
| Category             | Previous | With commit | Delta |
| -------------------: | -------: | ----------: | ----: |
| Expected passes      |    431  |     433 |  +2 |
| Unexpected failures  |    2 |  0 |    -2 | 
| Unexpected successes |        - |           - |     - | 
| Expected failures    |      16 |       16 |     - | 
| Unresolved testcases |      3 |         3 |     - |
| Untested testcases | 20 | 20 | - | 
| Unsupported tests    |      200 |        200 |     - |

### CODE REVIEW

**Review by jeremybennett — CHANGES_REQUESTED** [review]
This is fine, but needs more explanation in the commit message.  Is this due to the move to CV32E40pv2 encodings?  If so, the commit message should state this and reference the documentation.

Secondly, you still have 4 test failures. You need to explain what these are.

**Comment by MaryBennett** [comment]
Those failures were due to the incorrect hardware loop encodings fix in PR#70. Now that that is merged, I have rerun the tests.

**Comment by MaryBennett** [comment]
I have also updated the commit message

**Review by jeremybennett — APPROVED** [review]
All good to merge.

**Pull request merged**
