### PR TITLE
 Remove 'xcv' extension 

### PR DESCRIPTION
**Pull request by CharKeaney**
The CORE-V ISA Extension Naming specification was recently updated.
One of the consequences of this is that the option previously
called 'xcorev' (but implemented as 'xcv' presently due to the
prefix change) has been removed. However, the compiler does not
presently reflect this change. This patch removes the 'xcv' march
flag option so that the compiler and the CORE-V ISA Extension Naming
specification match.

See here for CORE-V ISA Extension Naming specification:
(https://github.com/openhwgroup/core-v-sw/blob/master/specifications/corev-isa-extension-naming.md)

	* bfd/elfxx-riscv.c: Remove 'xcv' extension.
	* gas/testsuite/gas/riscv/cv-alu-fail-march.l: Likewise.
	* gas/testsuite/gas/riscv/cv-alu-march-rv32i-xcv.d: Likewise.
	* gas/testsuite/gas/riscv/cv-alu-march-rv32i-xcv.s: Likewise.
	* gas/testsuite/gas/riscv/cv-bi-fail-march.l: Likewise.
	* gas/testsuite/gas/riscv/cv-bi-fail-march.s: Likewise.
	* gas/testsuite/gas/riscv/cv-bi-march-rv32i-xcv.d: Likewise.
	* gas/testsuite/gas/riscv/cv-bi-march-rv32i-xcv.s: Likewise.
	* gas/testsuite/gas/riscv/cv-bitmanip-march-xcv.d: Likewise.
	* gas/testsuite/gas/riscv/cv-bitmanip-march-xcv.s: Likewise.
	* gas/testsuite/gas/riscv/cv-elw-march-fail.l: Likewise.
	* gas/testsuite/gas/riscv/cv-elw-march-xcv.d: Likewise.
	* gas/testsuite/gas/riscv/cv-elw-march-xcv.s: Likewise.
	* gas/testsuite/gas/riscv/cv-hwlp-fail-march.l: Likewise.
	* gas/testsuite/gas/riscv/cv-hwlp-fail-march.s: Likewise.
	* gas/testsuite/gas/riscv/cv-hwlp-march-rv32i-xcv.d: Likewise.
	* gas/testsuite/gas/riscv/cv-hwlp-march-rv32i-xcv.s: Likewise.
	* gas/testsuite/gas/riscv/cv-mac-fail-march.l: Likewise.
	* gas/testsuite/gas/riscv/cv-mac-fail-march.s: Likewise.
	* gas/testsuite/gas/riscv/cv-mac-march-rv32i-xcv.d: Likewise.
	* gas/testsuite/gas/riscv/cv-mac-march-rv32i-xcv.s: Likewise.
	* gas/testsuite/gas/riscv/cv-mem-fail-march.l: Likewise.
	* gas/testsuite/gas/riscv/cv-mem-fail-march.s: Likewise.
	* gas/testsuite/gas/riscv/cv-mem-march-rv32i-xcv.d: Likewise.
	* gas/testsuite/gas/riscv/cv-mem-march-rv32i-xcv.s: Likewise.
	* gas/testsuite/gas/riscv/cv-simd-march-fail.l: Likewise.
	* gas/testsuite/gas/riscv/cv-simd-march-xcv.d: Likewise.
	* gas/testsuite/gas/riscv/cv-simd-march-xcv.s: Likewise.
	* include/opcode/riscv.h: Likewise.

### CODE REVIEW

**Comment by MaryBennett** [comment]
Looks good to me.

**Comment by NandniJamnadas** [comment]
@CharKeaney Could you post the before and after gas summary results for this patch?

**Comment by NandniJamnadas** [comment]
I have tested this patch and it all looks good. Ready to merge.

**Comment by CharKeaney** [comment]
> @CharKeaney Could you post the before and after gas summary results for this patch?

a749e1f71337e0d9befdd3f11daeccc60c4dc5d1 gas tests ( current corev-binutils-gdb ):
```
		=== gas Summary ===

# of expected passes		1270
# of expected failures		23
# of unsupported tests		9
```
3545d297f53b2a0b07a3a895189a55a5cfead8f8 gas tests ( after first commit ):
```
		=== gas Summary ===

# of expected passes		1270
# of expected failures		23
# of unsupported tests		9
```
8eeee236378acc68dbc27d8abcec665a4d1ff28d gas tests (after second commit ):
```
		=== gas Summary ===

# of expected passes		1262
# of expected failures		23
# of unsupported tests		9
```
Note the only reason I added the first commit is that the second depends on it. If the first is accepted in pr #75 before this (which I suggest) then the first commit not need to be merged as it will already be present.

**Comment by CharKeaney** [comment]
I updated the commit message to be more accurate.

**Comment by jeremybennett** [comment]
Thanks for the patch and review. Merging.

**Pull request merged**
