### PR TITLE
Renaming of cv.slet to cv.sle

### PR DESCRIPTION
**Pull request by MaryBennett**
For issue [#100](https://github.com/openhwgroup/corev-binutils-gdb/issues/100)

Files Changes:

  * gas/testsuite/gas/riscv/cv-alu-slet.d: Changed the name of cv.slet.
  * gas/testsuite/gas/riscv/cv-alu-sletu.d: Likewise.
  * opcodes/riscv-opc.c: Likewise.

### CODE REVIEW

**Comment by MaryBennett** [comment]
| Category             | With commit | 
| -------------------: | -------: | 
| Expected passes      |    1256 |   
| Unexpected failures  |       - |     
| Unexpected successes |        - | 
| Expected failures    |        25 |    
| Unresolved testcases |        - |     
| Unsupported tests    |      9 |

**Review by jeremybennett — CHANGES_REQUESTED** [review]
The corresponding `.s` files need updating so they test both the instruction _and_ the pseudo-instruction.

**Comment by MaryBennett** [comment]
I've changed the ```.s``` files to use both ```cv.slet``` and ```cv.sle```.

**Review by jeremybennett — APPROVED** [review]
This looks good to merge.

**Pull request merged**
