### PR TITLE
Support Zc extension in corev-binutils-gdb

### PR DESCRIPTION
**Pull request by pietraferreira**

### CODE REVIEW

**Comment by jeremybennett** [comment]
@MikeOpenHWGroup and Duncan Bees.  We are failing because one of the PLCT team, @yulong-plct doesn't have an Eclipse Committer Agreement in place. We'll reach out to him, but he might need assistance from you. Thanks.

**Comment by linsinan1995** [comment]
Thanks a lot for your work on it. 

I noticed that the table entry section is now in .rodata since f0c28cb819a032b518f9de678403ae9d5cfaffd7. However, both the table jump instruction (e.g. cm.jt 12) and the pointed table entry(e.g. 13th entry) require execution permission, and that's why they are put in .text section (there actually was a discussion about it in one zc* spec meeting).

some info: https://github.com/riscv/riscv-code-size-reduction/blob/main/Zc-specification/tablejump.adoc#table-jump-fault-handling

**Comment by yulong18** [comment]
I'm so sorry for this. I had update my e-mail address, please check it.

**Comment by jeremybennett** [comment]
> Thanks a lot for your work on it.
> 
> I noticed that the table entry section is now in .rodata since [f0c28cb](https://github.com/openhwgroup/corev-binutils-gdb/commit/f0c28cb819a032b518f9de678403ae9d5cfaffd7). However, both the table jump instruction (e.g. cm.jt 12) and the pointed table entry(e.g. 13th entry) require execution permission, and that's why they are put in .text section (there actually was a discussion about it in one zc* spec meeting).
> 
> some info: https://github.com/riscv/riscv-code-size-reduction/blob/main/Zc-specification/tablejump.adoc#table-jump-fault-handling

Thanks @linsinan1995 The branch has been updated, so the table now goes into `.text`. See commit [a52982c](https://github.com/openhwgroup/corev-binutils-gdb/pull/43/commits/a52982cf1c600f54931e25c98fdd2f7dcd1e1c5f)

**Comment by jeremybennett** [comment]
> I'm so sorry for this. I had update my e-mail address, please check it.
Thanks @yulong-plct That fixed the problem.

**Comment by jeremybennett** [comment]
All regression tests of Zc* now pass.  This branch is good to merge.

**Review by jeremybennett — APPROVED** [review]
This branch provides comprehensive support for Zc* 0.70.4.  There is good test coverage and all regression tests pass.

**Pull request merged**
