### PR TITLE
RISC-V: update match_func of cm.jt/cm.jalt to spec 1.0.

### PR DESCRIPTION
**Pull request by linsinan1995**
as mentioned at https://github.com/openhwgroup/corev-binutils-gdb/pull/65#issuecomment-1415356658, update the match_func field of cm.jt/cm.jalt.

with this patch, GAS can correctly accept `cm.jalt` with an index between 32 to 63.

### CODE REVIEW

**Comment by jeremybennett** [comment]
@linsinan1995 Thanks for spotting this.

Could I ask you to provide a GNU compliant commit message - it will make it easier when upstreaming. [This post](https://gcc.gnu.org/codingconventions.html#ChangeLogs) has some explanation.  If you look at the upstream commits, you'll see how people construct the messages.

With this change this is good to merge.

**Review by jeremybennett — CHANGES_REQUESTED** [review]
Technical content is good, just needs a GNU compliant commit message.

**Comment by linsinan1995** [comment]
> @linsinan1995 Thanks for spotting this.
> 
> Could I ask you to provide a GNU compliant commit message - it will make it easier when upstreaming. [This post](https://gcc.gnu.org/codingconventions.html#ChangeLogs) has some explanation. If you look at the upstream commits, you'll see how people construct the messages.
> 
> With this change this is good to merge.

Hi Jeremy. thanks for the info. The commit message now has been updated via contrib/mklog.py.

**Comment by jeremybennett** [comment]
Thanks @linsinan1995 - this will make life easier in future. All good to merge.

**Pull request merged**
